version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: lawblocks
    ports:
      - "3308:3306"
    environment:
      MYSQL_DATABASE: lawblocks
      MYSQL_USERNAME: root
      MYSQL_ROOT_PASSWORD: 1234
    volumes:
      - mysql_data:/var/lib/mysql
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    restart: always

volumes:
  mysql_data: